---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
    reviewers:
      - kare
    assignees:
      - kare
    labels:
      - ci
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    commit-message:
      prefix: build
    reviewers:
      - kare
    assignees:
      - kare
    labels:
      - build
